name: Magno Torres
favicon: null
layout_spectrum: 0.34900465374812484
typography_spectrum: 0.5994165029842407
title: Minha pagina inicial nesta grande rede mundial de computadores
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.47654440766200423
  lightness: 0.0365460142493248
  saturation: 0.03385644964873791
  rhythmicContrast: 0.21727378433570266
purpose: []
